using System.Collections.Generic;

namespace Fintrak.TRMS.FormNXPResponseDto
{
    // Root myDeserializedClass = JsonConvert.DeserializeObject<Root>(myJsonResponse);
    public class ResponseResult
    {
        public int id { get; set; }
        public object createdAt { get; set; }
        public object updatedAt { get; set; }
        public object archivedAt { get; set; }
        public object contact { get; set; }
        public object tin { get; set; }
        public int year { get; set; }
        public object formType { get; set; }
        public string statusCode { get; set; }
        public object status { get; set; }
        public object applicationNumber { get; set; }
        public object lastApplicationNumber { get; set; }
        public object formNumber { get; set; }
        public object formNumberSerial { get; set; }
        public object cancellationNumberSerial { get; set; }
        public object extensionNumberSerial { get; set; }
        public object formNumberAssignedDate { get; set; }
        public object amendmentNumberSerial { get; set; }
        public bool amendmentInit { get; set; }
        public bool cancelled { get; set; }
        public bool isDeleted { get; set; }
        public object expireAt { get; set; }
        public object expiryPeriod { get; set; }
        public object dateSubmitted { get; set; }
        public bool activeProcess { get; set; }
        public object currentStageDate { get; set; }
        public object processReset { get; set; }
        public object currentPVSVersion { get; set; }
        public object consigneeName { get; set; }
        public object consigneeEmail { get; set; }
        public object consigneePhone { get; set; }
        public object consigneeAddressLine1 { get; set; }
        public object consigneeAddressLine2 { get; set; }
        public object consigneeAddressCity { get; set; }
        public object consigneeAddressState { get; set; }
        public object consigneeCountry { get; set; }
        public object byOrderOf { get; set; }
        public object nepcNumber { get; set; }
        public object cacNumber { get; set; }
        public object licenseNumber { get; set; }
        public object rcNumber { get; set; }
        public object accountNumber { get; set; }
        public object accountNumberPreAmend { get; set; }
        public object processingFeeAccountNumber { get; set; }
        public object processingFeeAccountNumberPreAmend { get; set; }
        public object sector { get; set; }
        public object numOfItemsExpected { get; set; }
        public object exchangeRate { get; set; }
        public object exchangeRateApplicantCurrency { get; set; }
        public object totalNetWeight { get; set; }
        public object totalNetWeightExporter { get; set; }
        public object ncsTotalNetWeight { get; set; }
        public object meaTotalNetWeight { get; set; }
        public object totalGrossWeight { get; set; }
        public object totalGrossWeightExporter { get; set; }
        public object ncsTotalGrossWeight { get; set; }
        public object meaTotalGrossWeight { get; set; }
        public object totalQuantity { get; set; }
        public object totalQuantityExporter { get; set; }
        public object ncsTotalQuantity { get; set; }
        public object meaTotalQuantity { get; set; }
        public object dprTotalQuantity { get; set; }
        public object totalCF { get; set; }
        public object totalFreightCharges { get; set; }
        public object totalFoB { get; set; }
        public object totalFoBExporter { get; set; }
        public object totalDollarFoBExporter { get; set; }
        public object totalDollarFoB { get; set; }
        public object nessLevyPayable { get; set; }
        public object nessLevyPaymentPercent { get; set; }
        public object shipmentsCompleted { get; set; }
        public object endShipmentsRequestApproved { get; set; }
        public object endShipmentsRequestDate { get; set; }
        public object endShipmentsRequestReason { get; set; }
        public object designatedBank { get; set; }
        public object designatedBankPreAmend { get; set; }
        public object processingBank { get; set; }
        public object processingBankPreAmend { get; set; }
        public object processingBankBranch { get; set; }
        public object processingBankBranchPreAmend { get; set; }
        public object country { get; set; }
        public object countryPreAmend { get; set; }
        public object countryExporter { get; set; }
        public object inspectionLocation { get; set; }
        public object inspectionLocationPreAmend { get; set; }
        public object transportationMode { get; set; }
        public object transportationModePreAmend { get; set; }
        public object portShipment { get; set; }
        public object portShipmentPreAmend { get; set; }
        public object loadingTerminal { get; set; }
        public object loadingTerminalPreAmend { get; set; }
        public object currency { get; set; }
        public object currencyPreAmend { get; set; }
        public object paymentMode { get; set; }
        public object paymentModePreAmend { get; set; }
        public object pia { get; set; }
        public object piaPreAmend { get; set; }
        public object ncs { get; set; }
        public object ted { get; set; }
        public object monitoringMea { get; set; }
        public object monitoringMeaPreAmend { get; set; }
        public object tempShippingLine { get; set; }
        public object tempShippingLinePreAmend { get; set; }
        public object dpr { get; set; }
        public List<object> nonInspectionReasons { get; set; }
        public List<object> pvsResponses { get; set; }
        public List<object> failedInspections { get; set; }
        public List<object> permits { get; set; }
        public List<object> attachments { get; set; }
        public object extension1PreStatusCode { get; set; }
        public object extension1ExpirationDate { get; set; }
        public object extension1Number { get; set; }
        public object extension1Reason { get; set; }
        public bool extension1Init { get; set; }
        public bool extension1Complete { get; set; }
        public object extension1RequestDate { get; set; }
        public object extension1CompletedDate { get; set; }
        public bool dueExtension1 { get; set; }
        public object extension2PreStatusCode { get; set; }
        public object extension2ExpirationDate { get; set; }
        public object extension2Number { get; set; }
        public object extension2Reason { get; set; }
        public bool extension2Init { get; set; }
        public bool extension2Complete { get; set; }
        public object extension2RequestDate { get; set; }
        public object extension2CompletedDate { get; set; }
        public bool dueExtension2 { get; set; }
        public object preCancellationRequestStatus { get; set; }
        public object cancellationNumber { get; set; }
        public object cancellationReason { get; set; }
        public bool cancellationInit { get; set; }
        public bool cancellationComplete { get; set; }
        public object cancellationRequestDate { get; set; }
        public object cancellationCompletedDate { get; set; }
        public object initialShipment { get; set; }
        public object shipmentTmp { get; set; }
        public List<object> shipments { get; set; }
        public object lockedBy { get; set; }
        public List<object> amendments { get; set; }
        public List<object> workflowNotes { get; set; }
        public object preAmendmentRequestStatus { get; set; }
        public object amendmentNumber { get; set; }
        public object amendmentReason { get; set; }
        public bool amendmentComplete { get; set; }
        public object amendmentRequestDate { get; set; }
        public object amendmentCompletedDate { get; set; }
        public List<object> amendmentAttachments { get; set; }
        public object amendmentHistory { get; set; }
        public object einvoice { get; set; }
        public bool oilExport { get; set; }
    }

    public class NXPApprovalResponseDto
    {
        public int responseCode { get; set; }
        public string responseMessage { get; set; }
        public ResponseResult responseResult { get; set; }
    }


}
